### PR TITLE
Add Feedback page

### PR DESCRIPTION
**Pull request by Jeffkungu**
#### What does this PR do?
Add Feedback page to the settings menu page
#### Description of Task to be completed?
Add a form to the feedback page
#### How should this be manually tested?
After cloning the repo, run the app on android studio, click the settings menu then click on feedback. This should display a form which users can input information related to their feedback

### CODE REVIEW

**Comment by phillipahereza** [comment]
@Jeffkungu could you attach a screenshot.
And where is the feedback sent to? Could you direct it to support@codeforafrica.org and cc. phillip@codeforuganda.org

**Comment by Jeffkungu** [comment]
screen shot 2017-08-14 at 16 29 26
Here is how it looks.

**Comment by phillipahereza** [comment]
@Jeffkungu does this actually send the emails? Have you tested that part + please carefully read the description on the [trello card](https://trello.com/c/fHFXU4Z1/25-feedback-page). I asked you to automatically append the OS Version and the app version to the feedback email content

**Comment by Jeffkungu** [comment]
Yes it does I could demonstrate it to you on the call.

**Pull request closed without merging**
