### PR TITLE
Ft uploading media

### PR DESCRIPTION
**Pull request by mugiwaramunyi**
## What does this PR do?

Allows users to upload their media files to CR's database via the API endpoint 'stories/media/'

## Description of Task to be completed?
Create feature functionality to allow the user to upload media to the specified endpoint.

## How should this be manually tested?
- Clone the Repo
- Run Android Studio (AS)
- Run the app in AS
- Login with Facebook and go to the Assignments Detail Activity
- Click on the 'Start Reporting Button'
- Fill in some dummy data in all the Story fields and click on the 'Upload' Button
image

- Then proceed to upload some media by clicking the upload media button.
image

- That's it! You're files should be on the Citizen Reporter database.

## Background information to provide
- Careful when trying to upload to an API built using Django 1.11.2 that hasn't run migrations, if your server crashes with a `AttributeError: 'NoneType' object has no attribute 'is_relation'` downgrade to Django 1.10.7 and you should be fine.

### CODE REVIEW

**Comment by phillipahereza** [comment]
Correct me if I am wrong but it seems you're only uploading one media file.

**Comment by mugiwaramunyi** [comment]
Just seen this message @phillipahereza, yes the feature uploads one file at a time.

**Comment by mugiwaramunyi** [comment]
Hey @phillipahereza  haven't gotten a response, would you like the app to upload multiple files? If so, I think the django endpoint only allows for one file to be uploaded at a time.

**Comment by phillipahereza** [comment]
Probably run them in a loop in the background

**Comment by mugiwaramunyi** [comment]
Makes sense 🤔

**Comment by mugiwaramunyi** [comment]
@phillipahereza The function works now for multiple uploads, however there is a problem with the way files are being saved to local storage, such that the path generated when saving is raising a File not Found Exception, I looked through the code base for the method that stores captured media but I could not find it I think it's missing a  `.mkdirs()` method....If you could point me in the right direction I'd be grateful.

**Pull request closed without merging**
