### PR TITLE
Add Slide To Delete Animation

### PR DESCRIPTION
**Pull request by Jeffkungu**
#### What does this PR do?
Adds slide to delete feature with an animation that is displayed during the process of deleting a story.
#### Description of Task to be completed?
User should be able to slide a story card on the stories fragment to delete it 
#### How should this be manually tested?
After cloning the repo:
- Run the App on Android Studio and sign up with your Facebook account.
- Add a story/stories.
- Go to the stories activity and try deleting a story by sliding your finger to the left across a given story in the list.

### CODE REVIEW

**Comment by Jeffkungu** [comment]
Hey @phillipahereza kindly let me know if there is anything you'd want me to add or omit.

**Comment by phillipahereza** [comment]
The story are removed from the recycler view but not the database, when I open the stories fragment after deleting them, the reappear. Fix that

ezgif-4-747a482f55

**Comment by Jeffkungu** [comment]
Okay.

**Comment by Jeffkungu** [comment]
Hi @phillipahereza I had to add a new column to the database that contains a value representing the position of the story in the ListView. I could not delete the stories using their primary keys from the db.

**Pull request closed without merging**
