### PR TITLE
Ft Camera + photo overlay

### PR DESCRIPTION
**Pull request by mugiwaramunyi**
## **What does this PR Do?**
- This PR adds a camera feature to the Citizen Reporter app
- This feature utilizes the new camera2 API
- The feature also adds an overlay over the camera showing the user how to take a photo

## **Description of the task to be completed?**
- The assignment details activity has media buttons for adding the required type of media. On click of the image button, user is requested to pick a scene then the scene is overlaid on the camera to help the user capture the image.

## **Any background context to provide?**
- The overlay feature currently only has one functional overlay pending clarification of which images to use where.

### CODE REVIEW

**Comment by phillipahereza** [comment]
Hey sorry for the delay but here are the labelled overlays cc @Jeffkungu 

**Environment**
environment

**Candid**
candid

**Reaction/Interaction**
reaction interaction

**Signature**
signature

**Portrait**
portrait

**Comment by mugiwaramunyi** [comment]
Cool noted :+1:

**Comment by phillipahereza** [comment]
citizenreporterandroid-splashactivity-08262017120044
Dude I thought we decided you were going to make the overlay cover the whole screen, you've not considered any of my feedback 😡

**Comment by mugiwaramunyi** [comment]
Hey @phillipahereza so sorry I didn't check this. When I added the multiple overlays I forgot to format them to fit the screen, I'll have this ready for you today. Please don't be mad 😅

**Pull request closed without merging**
