### PR TITLE
Implement View Pager

### PR DESCRIPTION
**Pull request by Jeffkungu**
#### What does this PR do?
Implements ViewPager for the Fragments.
#### Description of Task to be completed?
Allow users to navigate from one page to another by swiping finger across the screen or pressing on desired page title. 
#### How should this be manually tested?
After cloning the repo run the application on an android device then signup with a Facebook or google account. Move to the Assignments, Stories and Settings page by swiping your finger to the left or right. You can also move to the desired page by tapping on the page title on top of the screen

### CODE REVIEW

**Comment by Jeffkungu** [comment]
screen shot 2017-09-26 at 10 57 05
This is how the screen looks like when user is on the Assignments page.

**Comment by Jeffkungu** [comment]
screen shot 2017-09-26 at 10 57 30
This is hoe the screen looks like when user is on the Stories page.

**Comment by phillipahereza** [comment]
@Jeffkungu the inactive page titles should be off white, maybe grey then white when active

**Comment by Jeffkungu** [comment]
@phillipahereza okay, let me work on it.

**Comment by Jeffkungu** [comment]
Hi @phillipahereza I have made a small change in the TabLayout, the other option would have been creating a custom  view (.xml file) for the TabLayout then write methods for the selected page behaviour, but that would be a lot of code for a simple functionality..

**Comment by Jeffkungu** [comment]
@phillipahereza Here is how it looks for different pages selected..
screen shot 2017-09-26 at 12 53 45

screen shot 2017-09-26 at 12 54 04

screen shot 2017-09-26 at 12 54 37

**Comment by Jeffkungu** [comment]
I've noticed the white and the dark grey have a wide margin, this looks better..

screen shot 2017-09-26 at 13 59 25

**Pull request closed without merging**
