### PR TITLE
Ft preview media

### PR DESCRIPTION
**Pull request by EdwinKato**
## PR Status
**READY**

## Story
https://trello.com/c/G1Zxu1Yt/38-tapping-an-a-attachment-should-preview-the-attachment

## Added Migrations
NO

## Description
I have added functionality to preview the attachments added by the user in the storyboard activity. These attachments can be in the form of images, audio files and video files. The user can now review any of the attachments within the app before uploading.

The video and image files can be played straight in the app while the images can also be previewed directly.

## New Packages Added
[] UniversalVideoView

## Related PRs
None

## Deploy Notes
Clone the repository and build the project in your development environment i.e Android Studio or eclipse

## Impacted Areas in Application
* The storyboard activity

## Screenshots

screenshot_20170928-140731
screenshot_20170928-140802
screenshot_20170928-140808
screenshot_20170928-140811
screenshot_20170928-142309
screenshot_20170928-142314

### CODE REVIEW

**Comment by phillipahereza** [comment]
@EdwinKato 
1. have you tested the app?
2. does it still upload media as expected?
3. Does it still display the media, after the story has been uploaded?

**Comment by phillipahereza** [comment]
@EdwinKato I realized we're not saving the local file paths of the media users upload. When a user opens their story after uploading it, they'll have to download it a new. I am going to work on saving the local file paths and then you'll fetch the update and modify your PR accordingly. Will be done by Monday

**Comment by phillipahereza** [comment]
@EdwinKato when previewing media that is no longer exists on the device memory, are you downloading it?

**Comment by EdwinKato** [comment]
@phillipahereza , i just pass the URL to the resource. I am not sure if its downloaded to the device. I think a better option would be to have 2urls for each attachment whereby a local one is used by default and the remote one is only used if the user deleted the attachment.

**Comment by phillipahereza** [comment]
☝️ @EdwinKato that's what I am working on

**Comment by EdwinKato** [comment]
@phillipahereza I have incorporated saving local media file paths with this PR. I will start using the PR template for future PRs since this was created before.

**Pull request merged**
